"""empty message

Revision ID: 2e4a0dd1f46f
Revises: 
Create Date: 2022-08-26 16:28:17.191259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4a0dd1f46f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite',
    sa.Column('FavId', sa.Integer(), nullable=False),
    sa.Column('UsPhId', sa.Integer(), nullable=False),
    sa.Column('PostId', sa.Integer(), nullable=False),
    sa.Column('ShopId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('FavId')
    )
    op.drop_table('migrate_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migrate_version',
    sa.Column('repository_id', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('repository_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repository_id', name='migrate_version_pkey')
    )
    op.drop_table('favourite')
    # ### end Alembic commands ###
