"""empty message

Revision ID: 469ab6f7212d
Revises: 00fddf3447b8
Create Date: 2022-09-04 22:43:35.389994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469ab6f7212d'
down_revision = '00fddf3447b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery', 'UpdateDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('subscribe', sa.Column('UsPhIdForSubscr', sa.Integer(), nullable=True))
    op.alter_column('subscribe', 'ShopId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('subscribe', 'UsLegId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribe', sa.Column('UsLegId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('subscribe', 'ShopId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('subscribe', 'UsPhIdForSubscr')
    op.alter_column('delivery', 'UpdateDate',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
