"""empty message

Revision ID: 534ec3ec4685
Revises: a7b6eaec2a2f
Create Date: 2022-09-06 20:09:52.311499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534ec3ec4685'
down_revision = 'a7b6eaec2a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backet', sa.Column('CreateDate', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backet', 'CreateDate')
    # ### end Alembic commands ###
