"""empty message

Revision ID: a7b6eaec2a2f
Revises: b0c8dcf32e5e
Create Date: 2022-09-06 19:35:44.964764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b6eaec2a2f'
down_revision = 'b0c8dcf32e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourite', sa.Column('CreateDate', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favourite', 'CreateDate')
    # ### end Alembic commands ###
