"""empty message

Revision ID: b0c8dcf32e5e
Revises: 469ab6f7212d
Create Date: 2022-09-05 16:53:43.007082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c8dcf32e5e'
down_revision = '469ab6f7212d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('ShopId_p', sa.Integer(), nullable=True))
    op.alter_column('comment', 'UsPhId_c',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('comment', 'UsLegId_c')
    op.drop_column('comment', 'UsLegId_p')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('UsLegId_p', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('UsLegId_c', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('comment', 'UsPhId_c',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('comment', 'ShopId_p')
    # ### end Alembic commands ###
