"""empty message

Revision ID: dafce01ef08b
Revises: 534ec3ec4685
Create Date: 2022-09-07 11:43:46.353342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafce01ef08b'
down_revision = '534ec3ec4685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'UsLegNickName')
    op.drop_column('order', 'UsLegId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('UsLegId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('UsLegNickName', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
