"""empty message

Revision ID: df4a7bd12f70
Revises: 95f9076d86cc
Create Date: 2022-08-29 16:46:13.703711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4a7bd12f70'
down_revision = '95f9076d86cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourite', sa.Column('ProductFlg', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favourite', 'ProductFlg')
    # ### end Alembic commands ###
